[package]
name = "mach2"
version = "0.4.1"
license = "BSD-2-Clause OR MIT OR Apache-2.0"
description = "A Rust interface to the user-space API of the Mach 3.0 kernel that underlies OSX."
repository = "https://github.com/JohnTitor/mach2"
readme = "README.md"
keywords = ["kernel", "macos", "darwin"]
categories = ["api-bindings", "external-ffi-bindings", "no-std", "os"]
edition = "2015"
include = ["src/**/*", "LICENSE-*", "README.md"]

[badges]
maintenance = { status = "passively-maintained" }

[target.'cfg(any(target_os = "macos", target_os = "ios"))'.dependencies]
libc = { version = "0.2", default-features = false }

[features]
default = []
# Uses newer APIs
unstable = []

[workspace]
members = ["mach-test"]

[package.metadata.docs.rs]
default-target = "x86_64-apple-darwin"
