max_width = 120
fn_call_width = 110
attr_fn_like_width = 95
imports_granularity = "Crate"
struct_lit_single_line = true
struct_lit_width = 65
unstable_features = true
version = "Two"
group_imports = "StdExternalCrate"
reorder_imports = true
wrap_comments = true
normalize_comments = true
reorder_impl_items = true
condense_wildcard_suffixes = true
enum_discrim_align_threshold = 20
use_field_init_shorthand = true
format_strings = true
format_code_in_doc_comments = true
format_macro_matchers = true
